backup:
  delay_minutes: 60
  max_copies: 3

  destination: "backups"
  folders:
    - "world"
    - "world_nether"
    - "world_the_end"
    - "plugins"
  files:
    - "server.properties"
    - "eula.txt"
